version: "3"

services:
  twitter:
    container_name: "twitter"
    build:
      context: .
      dockerfile: Dockerfile.twitter
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_HOST=selenium-chrome
    networks:
      - my-network
    command: "python /usr/src/app/twitter.py"

  instagram:
    container_name: "instagram"
    build:
      context: .
      dockerfile: Dockerfile.insta
    command: "python /home/app/bot.py"

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    networks:
      - my-network

networks:
  my-network: