version: "3"

services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    networks:
      - my-network
    environment:
      - SE_VNC_PASSWORD=1


  twitter:
    container_name: "twitter"
    build:
      context: .
      dockerfile: Dockerfile.twitter
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_HOST=selenium-chrome
    networks:
      - my-network
    command: "python /usr/src/app/twitter.py"

  imager:
    container_name: "imager"
    build:
      context: .
      dockerfile: Dockerfile.twitter
    command: "python /usr/src/app/main.py"
    volumes:
      - "./media:/usr/src/app/media"

  instagram:
    container_name: "instagram"
    build:
      context: .
      dockerfile: Dockerfile.insta
    command: "python /home/app/bot.py"

networks:
  my-network: